### ISSUE TITLE
Move dev dependencies to `[dependency-groups]`

### ISSUE THREAD

**Issue by baggiponte** [rich-iannone/pointblank#1]
[PEP 735](https://peps.python.org/pep-0735/) was accepted and now there's a place for all the dependencies that are not meant to be installed as core or optional dependencies (e.g. `[uv] pip install 'pointblank[sql]'`). You would just need to replace `[project.optional-dependencies]` with `[dependency-groups]` here.

[ref](https://github.com/rich-iannone/pointblank/blob/4618f0d76a5bd0ba15fa07b04e7076c369ade7d4/pyproject.toml#L47C1-L64C2)

In case you use uv, it [already supports this](https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-groups), so if you do `uv add --dev` this is the default place where these will end up.

This also enables you to split dev dependencies from docs, benchmarks, etc.

By the way, sick project!

**Comment by rich-iannone** [comment]
Sorry for the delay in answering but this is great advice and I'm going to try it out!

**Comment by baggiponte** [comment]
Thank you very much! I meant to suggest a PR but was super tight with xmas deadlines. Thanks for the responsiveness!
