### ISSUE TITLE
getting started simple dataset

### ISSUE THREAD

**Issue by wil337** [rich-iannone/pointblank#12]
Hi Rich, great package.
I'm having issues with it working on a simple example. What am I missing?

```
import pointblank as pb
data = pd.DataFrame({'a': [1,2,3]})
pb.Validate(data)
```
IndexError: list index out of range
File [c:\Repos\asxanalysis\.venv\Lib\site-packages\IPython\core\formatters.py:406](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#), in BaseFormatter.__call__(self, obj)
    404     method = get_real_method(obj, self.print_method)
    405     if method is not None:
--> 406         return method()
    407     return None
    408 else:
Hide Traceback
File [c:\Repos\asxanalysis\.venv\Lib\site-packages\pointblank\validate.py:424](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#), in Validate._repr_html_(self)
    422 def _repr_html_(self) -> str:
--> 424     return self.get_tabular_report()._repr_html_()

File [c:\Repos\asxanalysis\.venv\Lib\site-packages\pointblank\validate.py:3834](vscode-file://vscode-app/c:/Program%20Files/Positron/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#), in Validate.get_tabular_report(self, title)
   3829 validation_info_dict = _validation_info_as_dict(validation_info=self.validation_info)
   3831 # Has the validation been performed? We can check the first `time_processed` entry in the
   3832 # dictionary to see if it is `None` or not; The output of many cells in the reporting table
   3833 # will be made blank if the validation has not been performed
-> 3834 interrogation_performed = validation_info_dict.get("proc_duration_s", [None])[0] is not None
   3836 # ------------------------------------------------
   3837 # Process the `type_upd` entry
   3838 # ------------------------------------------------
   3839 
   3840 # Add the `type_upd` entry to the dictionary
   3841 validation_info_dict["type_upd"] = _transform_assertion_str(
   3842     assertion_str=validation_info_dict["assertion_type"]
   3843 )

I'm using windows
pointblank 0.2.1

**Comment by wil337** [comment]
I guess we are not supposed to run pb.Validate by itself? the __repr__ gives an error. but when I run this, it will work.
```
pb.Validate(data).col_exists(columns=['a']).interrogate()
```

**Comment by rich-iannone** [comment]
Thanks for trying out the package, and for reporting this bug. It is definitely a bug (and I can reproduce the error on my machine) and it’s something that I will fix!

I’ll update so that you get an empty report (with a pointer to add validation steps). 

Thanks again for filing this issue :)

**Comment by rich-iannone** [comment]
@wil337 Should be fixed now and the new release will be available quite soon!
